land/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('estate/', include('estate.urls')),
]

user/urls.py
from django.urls import path
from user import views

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
]

user/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    PERMISSIONS = (
        ('0', 'Collaborator'),
        ('1', 'Admin'),
    )
    permissions = models.CharField(
        max_length=1,
        choices=PERMISSIONS,
        blank=True,
        default='0',
    )

user/views.py
from django.shortcuts import render, reverse, HttpResponse, HttpResponseRedirect
from user.models import User
# Create your views here.


def register(request):
    if request.method == 'POST':
        new_user = User(
            first_name=request.POST['first_name'],
            last_name=request.POST['last_name'],
            phone=request.POST['phone'],
            permissions=request.POST['permissions'],
        )
        new_user.save()
        return HttpResponseRedirect(reverse('user:login'))
    elif request.method == 'GET':
        template = 'user/register.html'
        return render(request, template)
    return HttpResponse('No es posible guardar!')


def login(request):
    if request.method == 'POST':
        try:
            user = User.objects.get(first_name=request.POST['first_name'], permissions=request.POST['permissions'])
        except User.DoesNotExist:
            return HttpResponse('Usuario no existe!!!')

        return HttpResponseRedirect(reverse('estate:index', kwargs={'user_pk': user.pk}))
    elif request.method == 'GET':
        template = 'user/login.html'
        return render(request, template)
    return HttpResponse('Method not allowed')

user/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V3</title>
	<meta charset="UTF-8">
    {% load static %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'imagesi/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

    {% block content %}
    {% endblock %}
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

user/templates/user/login.html
{% extends 'user/base.html' %}
{% block content %}

<div class="limiter">
		<div class="container-login100" style="background-image: url('images/bg-01.jpg');">
			<div class="wrap-login100">
				<form class="login100-form validate-form" action="{% url 'user:login' %}" method="POST">
                    {% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						Iniciar Sesión
					</span>

					<div class="wrap-input100 validate-input">
                        <label>Nombre:</label>
						<input   style="color: black;" class="input100" type="text" name="first_name" required>
					</div>
					<div class="form-group validate-input" data-validate="Enter password">
                        <label style="">Tipo de usuario:</label>
						<select name="permissions" class="input100" style="color: black;">
                            <option value="0">Colaborador</option>
                            <option value="1">Administrador</option>
                        </select>
						<span  data-placeholder="&#xf191;"></span>
					</div>
					<div class="container-login100-form-btn">
						<button type="submit" class="login100-form-btn">
							Iniciar Sesión
						</button>
					</div>
				</form>
                <a href="{% url 'user:register' %}" style="color: black; a:hover{color: white;}">¿Necesita una cuenta?</a>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

{% endblock %}

user/templates/user/register.html
{% extends 'user/base.html' %}
{% block content %}
<div class="limiter">
		<div class="container-login100" style="background-image: url('images/bg-01.jpg');">
			<div class="wrap-login100">
				<form class="login100-form validate-form" action="{% url 'user:register' %}" method="POST">
                    {% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						Registrarse
					</span>

					<div class="wrap-input100 validate-input">
                        <label>Nombre:</label>
						<input   style="color: black;" class="input100" type="text" name="first_name" required>
					</div>
                    <div class="wrap-input100 validate-input">
                        <label>Apellido:</label>
						<input   style="color: black;" class="input100" type="text" name="last_name" required>
					</div>
                    <div class="wrap-input100 validate-input">
                        <label>Teléfono:</label>
						<input   style="color: black;" class="input100" type="text" name="phone" required>
					</div>
					<div class="wrap-input100 validate-input" data-validate="Enter password">
                        <label style="">Tipo de usuario:</label>
						<select name="permissions" class="input100" style="color: black;">
                            <option selected>Seleccione...</option>
                            <option value="0">Colaborador</option>
                            <option value="1">Administrador</option>
                        </select>
						<span  data-placeholder="&#xf191;"></span>
					</div>
					<div class="container-login100-form-btn">
						<button type="submit" class="login100-form-btn">
							Registrarse
						</button>
					</div>
				</form>
                <a href="{% url 'user:login' %}" style="color: black; a:hover{color: white;}">¿Iniciar Sesión?</a>
			</div>
		</div>
	</div>

	<div id="dropDownSelect1"></div>
{% endblock %}