estate/urls.py
from django.urls import path
from estate import views

app_name = 'estate'
urlpatterns = [
    path('index/<int:user_pk>/', views.index, name='index'),
    path('actions/<int:user_pk>/', views.actions, name='actions'),
    path('new-land/<int:user_pk>/', views.new_land, name='new-land'),
    path('edit-land/<int:land_pk>/', views.edit_land, name='edit-land'),
    path('delete-land/<int:land_pk>/', views.delete_land, name='delete-land'),
    path('actions-plot/<int:user_pk>/', views.actions_plot, name='actions-plot'),
    path('new-plot/<int:user_pk>/', views.new_plot, name='new-plot'),
    path('edit-plot/<int:plot_pk>/', views.edit_plot, name='edit-plot'),
    path('delete-plot/<int:plot_pk>/', views.delete_plot, name='delete-plot'),
    path('actions-tree-admin/<int:user_pk>/', views.actions_tree_admin, name='actions-tree-admin'),
    path('actions-tree-user/<int:user_pk>/', views.actions_tree_user, name='actions-tree-user'),
    path('new-tree/<int:user_pk>/', views.new_tree, name='new-tree'),
    path('edit-tree/<int:tree_pk>/', views.edit_tree, name='edit-tree'),
    path('delete-tree/<int:tree_pk>/', views.delete_tree, name='delete-tree'),
    path('detail-tree-plot/<int:tree_pk>/', views.detail_tree_plot, name='detail-tree-plot'),
    path('new-tree-plot/<int:tree_pk>/', views.new_tree_plot, name='new-tree-plot'),
    path('detail-plot-land/<int:user_pk>/', views.detail_plot_land, name='detail-plot-land'),
    path('new-tree-user/<int:user_pk>/', views.new_tree_user, name='new-tree-user'),
    path('new-plot-admin/<int:user_pk>/', views.new_plot_admin, name='new-plot-admin'),
    path('detail-plot-admin/<int:user_pk>/', views.detail_plot_admin, name='detail-plot-admin'),
]

land/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('estate/', include('estate.urls')),
]

user/urls.py
from django.urls import path
from user import views

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
]

estate/models.py
from django.db import models

# Create your models here.


class Land(models.Model):
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    region = models.CharField(max_length=100)

    def __str__(self):
        return self.name + ' - ' + self.country + ' - ' + self.region


class Plot(models.Model):
    land = models.ForeignKey(Land, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    latitude = models.CharField(max_length=100)
    length = models.CharField(max_length=100)

    def __str__(self):
        return 'Parcela: ' + self.name + ' - ' + ' Finca: ' + self.land.name


class Tree(models.Model):
    plot = models.ForeignKey(Plot, on_delete=models.CASCADE)
    diameter = models.CharField(max_length=100)
    height = models.CharField(max_length=100)
    health = models.CharField(max_length=100)
    year = models.DateField()

    def __str__(self):
        return 'Plot: ' + self.plot.name + ' - ' + self.diameter + ' - ' + self.height

estate/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, reverse
from estate.models import Land, Plot, Tree
from user.models import User
import datetime
# Create your views here.

def index(request, user_pk):
    template = 'estate/index.html'
    context = {
        'lands': Land.objects.all(),
        'plots': Plot.objects.all(),
        'user': User.objects.get(pk=user_pk),
        'trees': Tree.objects.all(),
    }
    return render(request, template, context)


def actions(request, user_pk):
    template = 'estate/actions.html'
    context = {
        'lands': Land.objects.all(),
        'user_pk': user_pk,
        'num_lands': Land.objects.count(),
    }
    return render(request, template, context)


def new_land(request, user_pk):
    if request.method == 'POST':
        new_land = Land(
            name=request.POST['name'],
            country=request.POST['country'],
            region=request.POST['region'],
        )
        new_land.save()
        return HttpResponseRedirect(reverse('estate:actions', kwargs={'user_pk': user_pk}))
    elif request.method == 'GET':
        template = 'estate/new_land.html'
        return render(request, template, {'user_pk': user_pk})
    return HttpResponseRedirect('No se Puede guardar!')


def edit_land(request, land_pk):
    if request.method == 'POST':
        updated_land = Land.objects.get(pk=land_pk)
        updated_land.name = request.POST['name']
        updated_land.country = request.POST['country']
        updated_land.region = request.POST['region']
        updated_land.save()

        return HttpResponseRedirect(reverse('estate:actions', kwargs={'user_pk': land_pk}))
    elif request.method == 'GET':
        temlate = 'estate/edit_land.html'
        context = {
            'land': Land.objects.get(pk=land_pk),
            'user_pk': land_pk,
        }
        return render(request, temlate, context)
    return HttpResponse('No se puede atualizar')


def delete_land(request, land_pk):
    deleted_land = Land.objects.get(pk=land_pk)
    deleted_land.delete()

    return HttpResponseRedirect(reverse('estate:actions', kwargs={'user_pk': land_pk}))


def actions_plot(request, user_pk):
    template = 'estate/actions_plot.html'
    context = {
        'plots': Plot.objects.all(),
        'user_pk': user_pk,
        'num_plots': Plot.objects.count(),
    }
    return render(request, template, context)


def new_plot(request, user_pk):
    if request.method == 'POST':
        post_land = Land.objects.get(pk=request.POST['land'])
        new_plot = Plot(
            land=post_land,
            name=request.POST['name'],
            latitude=request.POST['latitude'],
            length=request.POST['length'],
        )
        new_plot.save()

        return HttpResponseRedirect(reverse('estate:actions-plot', kwargs={'user_pk': user_pk}))
    elif request.method == 'GET':
        template = 'estate/new_plot.html'
        context = {
            'lands': Land.objects.all(),
            'user_pk': user_pk,
        }
        return render(request, template, context)
    return HttpResponse('No se puede guardar!!!')


def new_plot_admin(request, user_pk):
    if request.method == 'POST':
        post_land = Land.objects.get(pk=request.POST['land'])
        new_plot = Plot(
            land=post_land,
            name=request.POST['name'],
            latitude=request.POST['latitude'],
            length=request.POST['length'],
        )
        new_plot.save()

        return HttpResponseRedirect(reverse('estate:detail-plot-admin', kwargs={'user_pk': user_pk}))
    elif request.method == 'GET':
        template = 'estate/new_plot_admin.html'
        context = {
            'lands': Land.objects.all(),
            'user_pk': user_pk,
        }
        return render(request, template, context)
    return HttpResponse('No se puede guardar!!!')


def edit_plot(request, plot_pk):
    if request.method == 'POST':
        post_land = Land.objects.get(pk=request.POST['land'])
        updated_plot = Plot.objects.get(pk=plot_pk)
        updated_plot.land = post_land
        updated_plot.name = request.POST['name']
        updated_plot.latitude = request.POST['latitude']
        updated_plot.length = request.POST['length']
        updated_plot.save()

        return HttpResponseRedirect(reverse('estate:actions-plot', kwargs={'user_pk': plot_pk}))
    elif request.method == 'GET':
        template = 'estate/edit_plot.html'
        land_plot = Plot.objects.get(pk=plot_pk)
        context = {
            'plot': Plot.objects.get(pk=plot_pk),
            'lands': Land.objects.all(),
            'land_instance': land_plot,
            'plot_pk': plot_pk,
        }
        return render(request, template, context)
    return HttpResponse('No se puede guardar')


def delete_plot(request, plot_pk):
    delete_plot = Plot.objects.get(pk=plot_pk)
    delete_plot.delete()

    return HttpResponseRedirect(reverse('estate:actions-plot', kwargs={'user_pk': plot_pk}))


def actions_tree_admin(request, user_pk):
    template = 'estate/actions_tree_admin.html'
    context = {
        'trees': Tree.objects.all(),
        'user_pk': user_pk,
        'num_trees': Tree.objects.count(),
    }
    return render(request, template, context)


def actions_tree_user(request, user_pk):
    template = 'estate/actions_tree_user.html'
    context = {
        'trees': Tree.objects.all(),
        'user_pk': user_pk,
        'num_trees': Tree.objects.count(),
    }
    return render(request, template, context)


def new_tree(request, user_pk):
    if request.method == 'POST':
        post_plot = Plot.objects.get(pk=request.POST['plot'])
        new_tree= Tree(
            plot=post_plot,
            diameter=request.POST['diameter'],
            height=request.POST['height'],
            health=request.POST['health'],
            year=request.POST['year'],
        )
        new_tree.save()

        return HttpResponseRedirect(reverse('estate:index', kwargs={'user_pk': user_pk}))
    elif request.method == 'GET':
        template = 'estate/new_tree.html'
        context = {
            'user_pk': user_pk,
            'plots': Plot.objects.all(),
        }
        return render(request, template, context)
    return HttpResponse('No se puede guardar')


def new_tree_user(request, user_pk):
    if request.method == 'POST':
        post_plot = Plot.objects.get(pk=request.POST['plot'])
        trees_plot = Tree.objects.filter(plot=post_plot)
        count = 0
        today_year = datetime.datetime.today().year
        for tree_plot in trees_plot:
            if today_year == tree_plot.year.today().year:
                count += 1
                print(count)
                print(tree_plot.year.today().year)
                print(today_year)

        if count <10:
            new_tree= Tree(
                plot=post_plot,
                diameter=request.POST['diameter'],
                height=request.POST['height'],
                health=request.POST['health'],
                year=request.POST['year'],
            )
            new_tree.save()
            return HttpResponseRedirect(reverse('estate:index', kwargs={'user_pk': user_pk}))
        else:
            HttpResponseRedirect(reverse('estate:new-tree-user', kwargs={'user_pk': user_pk}))

    elif request.method == 'GET':
        template = 'estate/new_tree_user.html'
        context = {
            'user_pk': user_pk,
            'plots': Plot.objects.all(),
        }
        return render(request, template, context)
    return HttpResponse('No se puede guardar')


def edit_tree(request, tree_pk):
        if request.method == 'POST':
            post_plot = Plot.objects.get(pk=request.POST['plot'])
            update_tree = Tree.objects.get(pk=tree_pk)
            update_tree.plot = post_plot
            update_tree.diameter = request.POST['diameter']
            update_tree.height = request.POST['height']
            update_tree.health = request.POST['health']
            update_tree.year = request.POST['year']
            update_tree.save()

            return HttpResponseRedirect(reverse('estate:actions-tree-admin', kwargs={'user_pk': tree_pk}))
        elif request.method == 'GET':
            template = 'estate/edit_tree.html'
            plot_tree = Tree.objects.get(pk=tree_pk)
            context = {
                'tree': Tree.objects.get(pk=tree_pk),
                'plots': Plot.objects.all(),
                'plot_instance': plot_tree,
                'tree_pk': tree_pk,
            }
            return render(request, template, context)
        return HttpResponse('No se Puede Guardar')


def delete_tree(request, tree_pk):
    delete_tree = Tree.objects.get(pk=tree_pk)
    delete_tree.delete()

    return HttpResponseRedirect(reverse('estate:actions-tree-admin', kwargs={'user_pk': tree_pk}))


def detail_tree_plot(request, tree_pk):
    template = 'estate/detail_tree_plot.html'
    n_plots = Plot.objects.all()
    num_trees = Tree.objects.count()

    trees = []

    for plot_tree in n_plots:
        trees.append({
            'trees': Tree.objects.filter(plot=plot_tree.pk),
            'plot_name': plot_tree.name,
            'plot_land': plot_tree.land.name,
        })
    return render(request, template, {'trees': trees, 'num_tress': num_trees, 'tree_pk': tree_pk})


def new_tree_plot(request, tree_pk):
    if request.method == 'POST':
        post_plot = Plot.objects.get(pk=request.POST['plot'])
        new_tree = Tree(
            plot=post_plot,
            diameter=request.POST['diameter'],
            height=request.POST['height'],
            health=request.POST['health'],
            year=request.POST['year'],
        )
        new_tree.save()
        return HttpResponseRedirect(reverse('estate:detail-tree-plot', kwargs={'user_pk': tree_pk}))

    elif request.method == 'GET':
        template = 'estate/new_tree_plot.html'
        plot_tree = Tree.objects.get(pk=tree_pk)
        context = {

estate/templates/estate/actions.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
		<title>Acciones</title>
		<meta charset="utf-8" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<h1>Acciones</h1>
						<p>Agregar, realizar cambios, eliminar etc...</p>
					</header>
				<!-- Main -->
					<div id="main">
                        {% for land in lands %}
							<section id="content" class="main">
								<h2><strong>{{ land.name }}</strong></h2>
                                <p>País: {{ land.country }}</p>
                                <p>Región: {{ land.region }}</p>
                                <button type="button" class="btn btn-warning"><a href="{% url 'estate:edit-land' land.pk %}">Editar</a></button>
                                <button type="button" class="btn btn-danger"><a href="{% url 'estate:delete-land' land.pk %}">Eliminar</a></button>
                            </section>
                        {% endfor %}
					</div>

				<!-- Footer -->
					<footer id="footer">
						<section>
							<h2>Fincas: {{ num_lands }}</h2>
							<ul class="actions">
                                <br><li><a href="{% url 'estate:new-land' user_pk %}" class="button" style="margin-top: 1em;">Nueva Finca</a></li>
                                <br><li><a href="{% url 'estate:index' user_pk %}" class="button" style="margin-top: 1em;">Regresar</a></li>
                            </ul>
						</section>
						<section>
							<h2>Hulera</h2>
								<dd>Ciudad de Guatemala</dd>
							<ul class="icons">
								<li><a href="#" class="icon brands fa-twitter alt"><span class="label">Twitter</span></a></li>
								<li><a href="#" class="icon brands fa-facebook-f alt"><span class="label">Facebook</span></a></li>
								<li><a href="#" class="icon brands fa-instagram alt"><span class="label">Instagram</span></a></li>
								<li><a href="#" class="icon brands fa-github alt"><span class="label">GitHub</span></a></li>
								<li><a href="#" class="icon brands fa-dribbble alt"><span class="label">Dribbble</span></a></li>
							</ul>
						</section>
						<p class="copyright">&copy; Design: <a href="http://apitec.io/" target="_blank">APITEC</a>.</p>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>

estate/templates/estate/actions_tree_admin.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
		<title>Acciones</title>
		<meta charset="utf-8" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">
		<div id="wrapper">
					<header id="header">
						<h1>Acciones</h1>
						<br><li><a href="{% url 'estate:detail-tree-plot' user_pk %}" style="margin-top: 1em;">Ver Por Parcelas</a></li>

					</header>
					<div id="main">
                        {% for tree in trees %}
							<section id="content" class="main">
								<h2><strong>No. {{ tree.id }}</strong></h2>
								<p>Diámetro {{ tree.diameter }}</p>
                                <p>Parcela: {{ tree.plot.name }}</p>
                                <p>Finca: {{ tree.plot.land.name }}</p>
                                <p>Altura: {{ tree.height }}</p>
                                <p>Salud: {{ tree.health }}</p>
                                <p>Año: {{ tree.year }}</p>
                                <button type="button" class="btn btn-warning"><a href="{% url 'estate:edit-tree' tree.pk %}">Editar</a></button>
                                <button type="button" class="btn btn-danger"><a href="{% url 'estate:delete-tree' tree.pk %}">Eliminar</a></button>
                            </section>
                        {% endfor %}
					</div>

				<!-- Footer -->
					<footer id="footer">
						<section>
							<h2>Árboles: {{ num_trees }}</h2>
							<ul class="actions">
                                <br><li><a href="{% url 'estate:new-tree' user_pk %}" class="button" style="margin-top: 1em;">Nuevo Árbol</a></li>
                                <br><li><a href="{% url 'estate:index' user_pk %}" class="button" style="margin-top: 1em;">Regresar</a></li>
                            </ul>
						</section>
						<section>
							<h2>Hulera</h2>
								<dd>Ciudad de Guatemala</dd>
							<ul class="icons">
								<li><a href="#" class="icon brands fa-twitter alt"><span class="label">Twitter</span></a></li>
								<li><a href="#" class="icon brands fa-facebook-f alt"><span class="label">Facebook</span></a></li>
								<li><a href="#" class="icon brands fa-instagram alt"><span class="label">Instagram</span></a></li>
								<li><a href="#" class="icon brands fa-github alt"><span class="label">GitHub</span></a></li>
								<li><a href="#" class="icon brands fa-dribbble alt"><span class="label">Dribbble</span></a></li>
							</ul>
						</section>
						<p class="copyright">&copy; Design: <a href="http://apitec.io/" target="_blank">APITEC</a>.</p>
					</footer>

			</div>
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>

estate/templates/estate/base.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>Hulera</title>
		<meta charset="utf-8" />
        {% load static %}
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}"/>
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">
            {% block content %}
            {% endblock %}
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>

estate/templates/estate/index.html
{% extends 'estate/base.html' %}
{% block content %}
<div id="wrapper">

				<!-- Header -->
                    {% load static %}
					<header id="header" class="alt">
						<span class="logo"><img src="{% static 'images/arbolito.svg' %}" style="width: 10em;" alt="" /></span>
						<h1>Hulera</h1>
						<p>Usuario: {{ user.first_name }} {{ user.last_name }}<br/>
					</header>

				<!-- Nav -->
					<nav id="nav">
						<ul>
							<li><a href="#intro" class="active">Introducción</a></li>
							<li><a href="#first">Fincas</a></li>
							<li><a href="#second">Parcelas</a></li>
							<li><a href="#cta">Árboles</a></li>
							<li><a href="{% url 'user:login' %}">Cerrar Sesión</a></li>
						</ul>
					</nav>

				<!-- Main -->
					<div id="main">

						<!-- Introduction -->
							<section id="intro" class="main">
								<div class="spotlight">
									<div class="content">
										<header class="major">
											<h2>Bienvenido al Sistema de Administración de Fincas</h2>
										</header>
										<p>Aquí podrá ver las Fincas y sus parcelas y la cantidad de Árboles en cada Parcela</p>
									</div>
									<span class="image"><img src="{% static 'images/finquita.jpg' %}" alt="" /></span>
								</div>
							</section>

						<!-- First Section -->
							<section id="first" class="main special">
								<header class="major">
									<h2>Fincas</h2>
								</header>
								<ul class="features">
                                    {% for land in lands %}
									<li>
									<span class="image"><img src="{% static 'images/finca.jpg' %}" style="width: 100%;" alt="" /></span>
										<h3>{{ land.name }}</h3>
                                        <p>Ubicada en: {{ land.country }}</p>
                                        <p>Región: {{ land.region }}</p>
									</li>
                                    {% endfor %}
								</ul>
								<footer class="major">
									<ul class="actions special">
                                        {% if user.permissions == '0' %}
                                        <li><button class="button" disabled><a href="" disabled>Acciones<br></a><p style="color:red; font-weight: bold;">No puedes realizar acciones</p></button></li>
                                        {% else %}
                                        <li><button class="button"><a href="{% url 'estate:actions' user.pk %}">Acciones</a></button></li>
                                        {% endif %}
									</ul>
								</footer>
							</section>

						<!-- Second Section -->
						<section id="second" class="main special">
								<header class="major">
									<h2>Parcelas</h2>
								</header>
								<ul class="features">
                                    {% for plot in plots %}
									<li>
									<span class="image"><img src="{% static 'images/parcela.jpg' %}" style="width: 100%;" alt="" /></span>
										<h3>{{ plot.name }}</h3>
										<p>Finca: {{ plot.land.name }}</p>
                                        <p>Latitud: {{ plot.latitude }}</p>
                                        <p>Longitud: {{ plot.length }}</p>
									</li>
                                    {% endfor %}
								</ul>
								<footer class="major">
									<ul class="actions special">
                                        {% if user.permissions == '0' %}
                                        <li><button class="button"><a href="{% url 'estate:detail-plot-land' user.pk %}">Ver en Orden <br></a></button></li>
                                        {% else %}
                                        <li><button class="button"><a href="{% url 'estate:actions-plot' user.pk %}">Acciones</a></button></li>
                                        {% endif %}
									</ul>
								</footer>
							</section>
							<section id="cta" class="main special">
								<header class="major">
									<h2>Árboles</h2>
								</header>
								<ul class="features">
                                    {% for tree in trees %}
									<li>
									<span class="image"><img src="{% static 'images/arboles.png' %}" style="width: 100%;" alt="" /></span>
										<h2><strong>Árbol No. {{ tree.id }}</strong></h2>
										<h3>Diámetro {{ tree.diameter }}</h3>
										<p>Parcela: {{ tree.plot.name }}</p>
                                        <p>Finca: {{ tree.plot.land.name }}</p>
                                        <p>Altura: {{ tree.height }}</p>
										<p>Salud: {{ tree.health }}</p>
										<p>Año: {{ tree.year }}</p>
									</li>
                                    {% endfor %}
								</ul>
								<footer class="major">
									<ul class="actions special">
                                        {% if user.permissions == '0' %}
                                        <li><button class="button"><a href="{% url 'estate:actions-tree-user' user.pk %}">Acciones</a></button></li>
                                        {% else %}
                                        <li><button class="button"><a href="{% url 'estate:actions-tree-admin' user.pk %}">Acciones</a></button></li>
                                        {% endif %}
									</ul>
								</footer>
							</section>

					</div>

				<!-- Footer -->
					<footer id="footer">
						<section>
							<ul class="icons">
								<li><a href="#" class="icon brands fa-twitter alt"><span class="label">Twitter</span></a></li>
								<li><a href="#" class="icon brands fa-facebook-f alt"><span class="label">Facebook</span></a></li>
								<li><a href="#" class="icon brands fa-instagram alt"><span class="label">Instagram</span></a></li>
								<li><a href="#" class="icon brands fa-github alt"><span class="label">GitHub</span></a></li>
								<li><a href="#" class="icon brands fa-dribbble alt"><span class="label">Dribbble</span></a></li>
							</ul>
						</section>
						<p class="copyright">&copy; Design: <a href="http://apitec.io/" target="_blank">APITEC</a>.</p>
					</footer>

			</div>
{% endblock %}